[package]
name = "rusthelpers"
version = "0.1.0"
edition = "2021"

[lib]
name = "rusthelpers"
crate-type = ["staticlib"]
# crate-type = ["cdylib"]   # For creating a dynamic library

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
